name: Build Docker Image

on:
  push:
    branches: [ main,workflows ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19.0'

    - name: install make
      run: apk add --no-cache make

    - name: build docker image
      run: make container

    - name: push docker image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: p4nospet/covidapi:latest
        registry: hub.docker.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}