name: Covid19 API deployment

on:
  push:
    branches: ["main"]

jobs:
  test:
    name: checkout and test
    runs-on: golang:1.19-alpine
    steps:
    - uses: actions/checkout@v3

    - name: Test
      run: go test -v ./...